### ISSUE TITLE
Warning in dbload

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#1]
Hi,

when I load data with option 'lower case', I get following warning.  (for Pre-Release-20170205-Beta)

_dq = dbload('./data/data_q.csv','case=','lower');
Warning: Characters can not be used in both whitespace and delimiter lists.
Removing delimiter chars from whitespace list._

In previous versions, it worked fine.

Thanks
Mirek

**Comment by jaromir-benes** [comment]
Fixed in 20170602-Beta.

**Comment by jaromir-benes** [comment]
Fixed in 20170602-Beta.
