### ISSUE TITLE
iriscleanup and help

### ISSUE THREAD

**Issue by alaingalli** [IRIS-Solutions-Team/IRIS-Toolbox#107]
Hey guys! I just downloaded (for the first time in 2 years) a new version of the toolbox and noticed that the iriscleanup function and the "-help" folder with the manual are not there anymore. Could you tell me how to find them again (and to cleanup a iris session)? Thanks a lot!

Best

Alain

**Comment by jaromir-benes** [comment]
Hi Alain

The iris session functions are now in an +iris package. This means that you
call
iris.startup
iris.cleanup
iris.get
iris.set
etc....

Regarding the reference manual, we're preparing a new html based version
(which will be available online and offline). Will be ready shortly.

Thank you

Jaromir

**Comment by alaingalli** [comment]
Thanks Jaromir!!
