### ISSUE TITLE
findeqtn using regular expression

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#11]
> findeqtn(m,'-rexp','P.*')'

produces error:

> Output argument "varargout{2}" (and maybe others) not assigned during call to "model/myfind".
Error in model/findeqtn (line 47)
[ varargout{1:numel(varargin)} ] = myfind(this, 'findeqtn', varargin{:});

solution is 
> [varargout{1:nargout}] = myfind(This,'findeqtn',varargin{:});

**Comment by jaromir-benes** [comment]
The flag -rexp will no longer be supported. Use the rexp( ) wrapper instead, e.g. findeqtn(m, rexp('P.*')).

**Comment by jaromir-benes** [comment]
Functions model/findeqtn and model/findname now throw an error when the obsolete '-rexp' flag is used. Use the rexp( ) wrapper instead for regular expressions.
