### ISSUE TITLE
model selection

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#117]
Is it possible to do model selection in IRIS? Is there a way to compute the marginal likelihood of the data given the model?

**Comment by jaromir-benes** [comment]
The approximate marginal data density can be calculated from a posterior simulator run, using the ```stats( )``` function; look for the ```mdd``` field in the output structure. See, for instance, the tutorial file ```estimate_params``` in [Simple SPBC Model Tutorial](https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model).
