### ISSUE TITLE
barcon bug

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#120]
Release-20180308 fixes #116, but produces error:
```
>> r=qq(2018,1:4);
>> barcon(r,Series(r,@rand));
Error using matlab.graphics.chart.primitive.Bar/get
There is no CData property on the Bar class.

Error in numeric.barcon (line 70)
    p = get(handlePositive(i), linkedProperties);

Error in TimeSubscriptable/implementPlot (line 82)
handlePlot = plotFun(axesHandle, xData, yData, specString{:}, unmatchedOptions{:});

Error in TimeSubscriptable/barcon (line 66)
            [varargout{1:nargout}] = implementPlot(@numeric.barcon, varargin{:});

Error in Series/barcon (line 56)
[varargout{1:nargout}] = barcon@TimeSubscriptable(varargin{:});
```

**Comment by jaromir-benes** [comment]
This looks line an older version of Matlab? Perhaps pre-2016?

**Comment by ikarib** [comment]
No, R2017a here. Also, colormap is not respected:
```
colormap([0 0 0; .5 .5 .5; 1 1 1])
barcon(r,[Series(r,@rand) Series(r,@rand) Series(r,@rand)]);
```

**Comment by jaromir-benes** [comment]
I found out there were a couple of not-so-minor changes in graphics between R2017a and R2017b. The barcon (and other plotting) functions should work now (in the repo, not a release yet). 

However, starting from 2017b, Matlab does not use the `ColorMap` in bar graphs any longer; the color mechanism in `bar( )` is now the same in as in `plot( )`, based on the `ColorOrder` instead.

The `barcon( )` function has therefore an option `ColorMap=` allowing the user to specify their own color maps, together with the option `EvenlySpread=` (if `true` the colors are evenly spread across the entire length of the color map; if `false` the colors are used in their specified order).
