### ISSUE TITLE
New syntax for inverse-gamma distribution

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#14]
Creating the inverse gamma distribution in IRIS requires the mean and standard deviation to be defined as inputs:
```
F = logdist.invgamma(MEAN,STD)
```
This limits the shape parameter alpha to be greater than two.

I suggest to add new syntax:
```
F = logdist.invgamma(NaN,NaN,A,B)
```
where A and B are shape and scale parameters (any positive numbers).

https://en.wikipedia.org/wiki/Inverse-gamma_distribution

**Comment by jaromir-benes** [comment]
Ok, good idea.

**Comment by ikarib** [comment]
Something like this works:
```
if nargin<3
    a = 2 + (mean_/std_)^2;
    b = mean_*(1 + (mean_/std_)^2);
else
    if a > 1
        mean_ = b/(a - 1);
    else
        mean_ = NaN;
    end
    if a > 2
        std_ = mean_/sqrt(a - 2);
    else
        std_ = NaN;
    end
end

```
