### ISSUE TITLE
Second or Higher order solution？

### ISSUE THREAD

**Issue by lnsongxf** [IRIS-Solutions-Team/IRIS-Toolbox#167]
Hi,

I have a question about IRIS toolbox, can the toolbox solve and estimate the model in second or higher order? Because there are many research emphasize the second order shocks now, like uncertainty shock.

If the answer is yes, that could be very wonderful.

Thanks,

Xiaofei Song

**Comment by ghost** [comment]
No, this toolbox hinges on the first-order solution. There is a way to handle nonlinearities in selective equations when simulating the model and that's it. This toolbox is useful for forecasting. For academic research, if you primarily need to solve and estimate a model in a higher order, then Dynare should suit you well.

**Comment by lnsongxf** [comment]
Thanks for your reply, Best.
