### ISSUE TITLE
bug in plotpp

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#18]
There is a bug in plotpp that doesn't allow setting figure options.
For example, the following code will not maximize figure to full screen size.
```
E.x = {0, -3, 3, logdist.normal(0,1)};
plotpp(E,[],[],'figure=',{'position=',get(0,'ScreenSize')});
```
To fix this, please move line 383 of +grfun\\plotpp.m:
> Fig = figure( );

to line 391 after doGraphicsOpt():
```
doGraphicsOpt( );
Fig = figure(figureOpt{:});
```
Also, plotpp will not plot the starting value as vertical stem (in the manual, plotInit = true, by default):
To fix this, change line 81 of +irisopt\\grfun.m:
```
'plotinit',true,@(x) islogicalscalar(x) || (iscell(x) && iscellstr(x(1:2:end))), ...
```

Please document the following plotpp options that are missing in the manual:
* axes
* figure
* subplot

**Comment by jaromir-benes** [comment]
Documentation to be completed later.

**Comment by ikarib** [comment]
The first plot is not affected by figure options.
Please change line 391 of +grfun\plotpp.m:
```
fig = figure( );
```
to
```
fig = figure(figureOpt{:});
```
