### ISSUE TITLE
dbload() with annual data in newer IRIS version

### ISSUE THREAD

**Issue by alaingalli** [IRIS-Solutions-Team/IRIS-Toolbox#188]
Hey there

I am having trouble when trying to import annual data with newer (2018/2019) versions of IRIS. 
With older IRIS versions, this syntax worked fine:

dbload('data.csv','dateFormat','YYYY')

Now it Imports empty time series.

Has anything changed in the dbload() function that I've missed?

CSV-File looks the following:

,ts1,ts2
2008,1,2
2009,1,2

Cheers

**Comment by jaromir-benes** [comment]
Hi

This was a bug in IRIS. It's been fixed in the latest release.

Thank you

Jaromir

**Comment by alaingalli** [comment]
Thanks Mirek!
