### ISSUE TITLE
Error when using Release-20190415

### ISSUE THREAD

**Issue by artt** [IRIS-Solutions-Team/IRIS-Toolbox#189]
I just updated my IRIS to the latest release. My code ran fine in 0328 release, but now I get this error calling filter:

	Error using model.filter
	The value of 'SolvedModel' is invalid. Method 'isSolved' is not defined for class 'model' or is removed from MATLAB's search path.

	Error in extend.InputParser/parse (line 37)
	            parse@inputParser(this, varargin{:});

	Error in model/filter (line 271)
	parser.parse(this, inputDatabank, filterRange, varargin{:});

	Error in main (line 58)
	[~, f] = filter(model_uip, d, round.rng.h);

**Comment by jaromir-benes** [comment]
Thanks for reporting this ones. Fixed in today's release. Best, Jaromir
