### ISSUE TITLE
Compatibility between tseries and Series?

### ISSUE THREAD

**Issue by artt** [IRIS-Solutions-Team/IRIS-Toolbox#191]
In older versions of IRIS (2015-ish), I believe results from `filter` and `simulate` (in `f.mean`, for example) are `tseries` objects. I recently updated IRIS and found that in newer versions of IRIS, `f.mean` contains `Series` objects instead.

Suppose `a` is a `Series` object and `b` is a `tseries` object, I get the following:

    plot([a, b])

works fine. But then...

	>> plot(a)

	ans = 

	  Line with properties:

	              Color: [0 0.4470 0.7410]
	          LineStyle: '-'
	          LineWidth: 0.5000
	             Marker: 'none'
	         MarkerSize: 6
	    MarkerFaceColor: 'none'
	              XData: [1×12 datetime]
	              YData: [1 1 1 1 1 1 1 1 1 1 1 1]
	              ZData: [1×0 double]

	  Show all properties

	>> hold on
	>> plot(b)
	Error using NumericTimeSubscriptable/plotSwitchboard (line 42)
	Values plotted against x-axis must be datetime values. To create datetime values, use the DATETIME function.

	Error in tseries.implementPlot (line 112)
	[plotHandle, isTimeAxis] = this.plotSwitchboard( plotFunc, ...

	Error in tseries/plot (line 85)
	[~, varargout{1:nargout}] = tseries.implementPlot(@plot, varargin{:});

and...

	>> plot(b)
	>> hold on
	>> plot(a)
	Error using NumericTimeSubscriptable/plotSwitchboard (line 42)
	Data inputs must match the axis configuration. A numeric axis must have numeric data inputs or data inputs which can be converted to
	double.

	Error in Series.implementPlot (line 72)
	[plotHandle, isTimeAxis] = this.plotSwitchboard( plotFunc, ...

	Error in Series/plot (line 20)
	            [varargout{1:nargout}] = Series.implementPlot(@plot, varargin{:});

I might have missed this, but should I use `Series` from now on? What's the difference between the two?

**Comment by tosapola** [comment]
https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/issues/108

Better work with the new class Series.
Starting IRIS with command iris.startup make Series the default class.
