### ISSUE TITLE
Release-20190513: error in srf() 

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#194]
got an error when using srf()
-----------------------------
Error using model.responseFunctions
The value of 'Model' is invalid. Undefined function 'isSolved' for input
arguments of type 'model'.

Error in extend.InputParser/parse (line 37)
            parse@inputParser(this, varargin{:});

Error in model/responseFunction (line 20)
parse(parser, this, time);

Error in model/srf (line 95)
[s, range, select] = responseFunction(this, time, func, select, opt);

Error in plot_model_properties (line 33)
s = srf(m,1:40);

**Comment by jaromir-benes** [comment]
Hi

This was a GitHub issue (unzipping the archives) mainly affecting Windows
systems. I created a patch for this in 20190513, and it looks to work fine
now.

Best
Jaromir

**Comment by tosapola** [comment]
Hi,

Not sure what you mean by GitHub issue.
On my machine, I tried 2-3 unzip tools but still got that error.
Could you please guide me to where to check if the upzipping works correctly? What file that we're looking for?

Best,
Tos

**Comment by jaromir-benes** [comment]
Hi

The 20190513 version should be now immune to the issue. I really do not
have any idea whatsoever. The solution was simply to rename one particular
file...

Do you still experience problems even with 20190513?

Best
Jaromir

**Comment by tosapola** [comment]
I have checked 2 latest version:
20190512 - OK
20190513 - failed
PS. I'm on Windows 10 & 2019a

**Comment by jaromir-benes** [comment]
That's weird. I'm now running a workshop in Brazil, and everyone on Windows
had problems with 20190512 but is ok with 20190513 (that was actually the
only reason I create 20190513). Could you please describe exactly what's
happening at your computer? Many thanks.

**Comment by tosapola** [comment]
I think I found it.
The unzipped 20190512 has isSolved.m.
The unzipped 20190513 has NO isSolved.m.
So I looked into the original zip files and here are screenshots...
![Sketch20190512](https://user-images.githubusercontent.com/26425023/57745397-2e761100-76f7-11e9-9c7e-6edd1928f24c.png)
![Sketch20190513](https://user-images.githubusercontent.com/26425023/57745401-33d35b80-76f7-11e9-9d3e-b81a6a58247a.png)
Also there are duplicated isSolved.m in 20190512.
I recall that we have a similar issue a while ago but cannot find a previous thread.

Best,
Tos

**Comment by tosapola** [comment]
> I think I found it.
> The unzipped 20190512 has isSolved.m.
> The unzipped 20190513 has NO isSolved.m.
> So I looked into the original zip files and here are screenshots...
> 
> 
> Also there are duplicated isSolved.m in 20190512.
> I recall that we have a similar issue a while ago but cannot find a previous thread.
> Best,
> Tos

Oops, sorry, that's what you has just renamed.

So let's go back to the error in the first comment. It happens when I call srf(). Something in the function srf() still refers to the old isSolved().

Best,
Tos

**Comment by tosapola** [comment]
> That's weird. I'm now running a workshop in Brazil, and everyone on Windows
> had problems with 20190512 but is ok with 20190513 (that was actually the
> only reason I create 20190513). Could you please describe exactly what's
> happening at your computer? Many thanks.
> …
Hi,

The error happens when I call srf() function as I posted above.
I have seen that you renamed isSolved() to beenSolved(). So there might be something in srf() that still refers to the old isSolved().

Best,
Tos

PS. Also look into the zip file of 20190512, there are duplicated isSolved.m files. That might be your issue with 20190512.

![Sketch20190512](https://user-images.githubusercontent.com/26425023/57909156-2b705180-78ac-11e9-9794-5e897c133d68.png)
