### ISSUE TITLE
Create AR series: arf function

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#198]
Hi,

when running arf function with these inputs, I get an error. If I try in in some old IRIS (March 2018 release), it works fine.

Thanks
Mirek

arf(Series(qq(2019,1),-.75), [1 -.5],0,qq(2019,2):qq(2019,4)); 

Undefined function or variable 'zData'.
Error in NumericTimeSubscriptable/arf (line 118)
    zData = repmat(zData, nPer, 1);

**Comment by jaromir-benes** [comment]
Fixed, will be out with the next release.
