### ISSUE TITLE
Reports that contain accents does not generate PDF

### ISSUE THREAD

**Issue by joaodimas** [IRIS-Solutions-Team/IRIS-Toolbox#199]
Creating a new report with an accent in its title causes a LaTeX compilation error due to encoding.

**Comment by joaodimas** [comment]
The cause is that Iris generates a tex file with ANSI charset. Modifying the charset to UTF-8 solves the problem.

I propose modifying the file utils\char2file.m to accept an additional argument (Encoding), and modifying the file +report\@reportobj\publish.m to pass the argument 'UTF-8' to the function char2file.

I'm attaching the corrected files (remove the .txt suffix).

[char2file.m.txt](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/3277075/char2file.m.txt)
[publish.m.txt](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/3277081/publish.m.txt)

**Comment by jaromir-benes** [comment]
Thanks. Will be fixed and out with the next release.

Best
Jaromir

**Comment by jaromir-benes** [comment]
A new option `Encoding=` was added to `char2file`, `file2char` and `report.publish`. You need to use this option explicitly (the default was not changed for backward compatibility reasons).
