### ISSUE TITLE
Detrend function (Matlab vs. IRIS)

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#2]
When I want to 'detrend' time series it calls Matlab function and not IRIS function. 

Thanks.
Mirek

**Comment by jaromir-benes** [comment]
Can you please post a code where the built-in detrend is called?

Thx
Jaromir

**Comment by MiroslavHlousek** [comment]
Sorry, it was my misinterpretation of the bug. Here is the error message when I want to detrend time series.  detrend(dq.unempl)

Error using double
Conversion to double from function_handle is not possible.

Error in tseries/rangedata (line 55)
    range = double(range);

Error in tseries/trend (line 65)
[ThisData,Range] = rangedata(This,Range);

Error in tseries/detrend (line 40)
This = This - trend(This,varargin{:});

**Comment by jaromir-benes** [comment]
Fixed in 201702016-Beta.

**Comment by Usukhbayar13** [comment]
is rangedata function available on IRIS 23?
