### ISSUE TITLE
configuration.mat handled by several users, is it risky?

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#200]
Hi Jaromir and Iris-team,

Again thank you for your help. 
I have a question about configuration.mat. Because we want to make sure everyone use the same IRIS, in the past, we created a version which is shared by all team's member in pointing the code of everyone to the same place. But now because we have configuration.mat file I have a concern, Is it risky to continue to use IRIS as the same way we use it before (with iris 2015). If yes what kind of issue we will face if we still go ahead with sharing.

![configuration](https://user-images.githubusercontent.com/22647406/59372331-443a1e80-8d15-11e9-94ab-f298bbb7f971.jpg)

**Comment by jaromir-benes** [comment]
Hi

That's a good question, indeed. The configuration object is primarily
stored using setappdata(0, ...) and accessed through getappdata(0, ...) in
each instance of a running Matlab. The Configuration.mat file is only a
backup file maintained in case the appdata(0, ...) get corrupted for
whatever reason - which is practically very unlikely to happen. So I'd say
you should be safe running IRIS from the same location on multiple
instances of Matlab. Of course, there might arise some unforeseen issues,
so don't hesitate to let me know immediately.

Best
Jaromir
