### ISSUE TITLE
Bugs with the options fsolve in sstate()

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#201]
Hi Jaromir,

When I used the option 'fsolve' in the function 'sstate' I have noticed an issue.
I noticed that section fsolve in /+solver/+block/Block.m seems have some comments and f is not defined anywhere. This is the results of my issues ( I used the release 20190612):

![issues_with_fsolve](https://user-images.githubusercontent.com/22647406/59619420-77572600-90f8-11e9-9f3a-c1c27cf5797f.jpg)

**Comment by jaromir-benes** [comment]
Fixed and out in today's release.
