### ISSUE TITLE
Error loading model file (R20190617)

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#202]
Hi,

Error loading model file with model() function. MATLAB says...

> Abstract classes cannot be instantiated.  Class 'model' inherits abstract
methods or properties but does not implement them.  See the list of methods
and properties that 'model' must implement if you do not intend the class to
be abstract.

Also the previous release (R20190612) has an issue too. It can read the model file but cannot display model object.

Best,
Tos

**Comment by jaromir-benes** [comment]
Hi Tos

Thanks for submitting this one. For some reasons I don't fully understand
this bug made it through out testing suite.

Will be fixed in the next release.

Jaromir
