### ISSUE TITLE
trec doesn't exist anymore

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#209]
Hi Jaromir,

It seems the function **trec()** doesn't exist anymore could you tell us if you have an equivalent or if it has the chance to back in the future.

Thanks

**Comment by jaromir-benes** [comment]
Hi,

the `trec` object relied on some internal Matlab features that were
removed/changed at some point in the past so the object stopped working.

There is a replacement class `TimeRecursive` that works as follows:

rangeToEval =  qq(2010,1):qq(2012,4);
tr = TimeRecursive(rangeToEval);

x = Series( );
y = Series( );
e = Series( );
x(qq(2009,4)) = 1;
y(qq(2009,4)) = 1;
e(rangeToEval) = randn(12, 1);

tr : 'x = 0.8*x{-1} + e';
tr : 'y = 0.5*y{-1} + e';

% or also

tr : { 'x = 0.8*x{-1} + e', 'y = 0.5*y{-1} + e' };

**Comment by mariusmjp** [comment]
Hi Jaromir,

Thanks for your quick answer another point I discovered it seems the new way doesn't support structure for example I can't do **d.**x = Series(); ..........; tr ='**d.**x = 0.8* **d.**x{-1} + e' . I'm obligate to create more steps,first in creating a temp variable which is used  and after assigne it to my variable inside the structure. Is it possible to improve this part ?

Thanks for all

**Comment by jaromir-benes** [comment]
Hi, you can use the reporting equations object rpteq, see the tutorial
files https://github.com/IRIS-Solutions-Team/Tutorial-Reporting-Equations
(start in read_me_first.m)
