### ISSUE TITLE
user-supplied time-varying stdcorr for presample

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#21]
Users can supply time-varying stdcorr of shocks (paths for standard deviations and cross-correlation coefficients) using 'vary=' option to Kalman filter. But in presample period stdcorr is overwriten with currently assigned stdcorr in the model object. Please fix this so that Kalman filter initializes the presample stdcorr using stdcorr from the first period of user-supplied database.

This can be done in line 183 of classlib\\@model\kalmanFilter.m
```
        stdcorri = s.stdcorr(:,1);
        s.stdcorr = [stdcorri, s.stdcorr];
```

**Comment by ikarib** [comment]
please fix

**Comment by jaromir-benes** [comment]
Time series for time-varying stds and corrs can now have a presample data point (i.e. observation at t-1 where t is the start of the filter range) which is used to initialize the Kalman filter.
