### ISSUE TITLE
Flexibility to change Steady Tolerance

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#211]
Hi Jaromir,

Thanks for everything you did until now. I have another proposition if you doesn't find any objection. Is it possible to give the flexibility to user to modify the Steady tolerance as you did with MSE for example. Because I found the steady tolerance too strict and I want to reduce it. 
For my side I changed the code of **tolerance()** a little bit for adding another section.
![Flexibility_to_handle_steady_tolerance](https://user-images.githubusercontent.com/22647406/62707278-17c21c00-b9bf-11e9-9890-f9387bed4c57.jpg)

**Comment by jaromir-benes** [comment]
Ok, will do.
