### ISSUE TITLE
VAR filter N step ahead forecasts stopped working

### ISSUE THREAD

**Issue by alexisakov** [IRIS-Solutions-Team/IRIS-Toolbox#214]
Attempts to execute the Serhat's Turkey VAR tutorial (https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/iris-toolbox-project/Serhats_Example_Simple_VAR_More_20130110.zip) lead to an error: 

[~,f00] = filter(v,g,starthist+2:endhist, ...
     'output=','pred','ahead=',4,'meanonly=',true);

Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in VAR/filter/doAssignOutp (line 232)
            iY0 = [nan(ny,p,s.ahead),iYInit];

Error in VAR/filter (line 160)
    doAssignOutp( );

**Comment by jaromir-benes** [comment]
Fixed
