### ISSUE TITLE
Error using feed.fred 

### ISSUE THREAD

**Issue by renaudst16** [IRIS-Solutions-Team/IRIS-Toolbox#217]
Hi, 

The fonction feed.fred does not work in the latest version of IRIS. I get the following error when I do the command: test=feed.fred('GDP')

![image](https://user-images.githubusercontent.com/55812409/65838501-d28cdd00-e2d1-11e9-853a-3a00bf4c915d.png)

The problem was not present in a previous version of IRIS I was using : IRIS-Toolbox-Pre-Release-20170320-Beta

That would be great if this could be fixed! Thank you.

**Comment by jaromir-benes** [comment]
Hi

This typo was fixed in today's release, 20190110. Note however that `feed.fred` is an obsolete function. The new replacement is `databank.fromFred(~)`.

Best
Jaromir
