### ISSUE TITLE
bug in dbplot

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#22]
> d.x=tseries(1:5,@rand);

This works:
> dbplot(d,1:5,{' "x" [x]'});

This doesn't:
> dbplot(d,1:5,{' "x", [x]'});

**Comment by jaromir-benes** [comment]
This is not a bug, this is the syntax required by `dbplot( )`.

**Comment by ikarib** [comment]
The second syntax was used in SPBC tutorial.

**Comment by jaromir-benes** [comment]
Ok, if you really want I'll include that back :))

**Comment by ikarib** [comment]
No, thanks. It was a typo in core PCE subplot.
