### ISSUE TITLE
Reference for convert/quadavg

### ISSUE THREAD

**Issue by Nic2020** [IRIS-Solutions-Team/IRIS-Toolbox#225]
Hi,

I am using a convert command based on quadratic interpolation that preserves the average of observations within each period, as follows:

ts_q = convert(ts_y,4,range(ts_y),'method=','quadavg','position=','centre');

I followed the code down to convert.m and down to the subfunction [y2, flag] = interpolateAndMatchEval(y1, n).

I was surprised to see that MATLAB's native interp1 actually does not support the quadavg method, despite specific posts on this on MATLAB Central (e.g. https://www.mathworks.com/matlabcentral/answers/356642-interpolation-keep-average-over-certain-range-to-fixed-value).

I think this interpolation method is brilliant, but I cannot find any reference on the web about it.

I would be most grateful if I could have a paper or any reference to read to understand this method better.

Thank you,

Nicholas

**Comment by jaromir-benes** [comment]
Hi Nicholas

I implemented the algorithm from EViews - it's described in the EViewd
manual (which is I believe publicly available; if not, I'll send you the
relevant pages.)

I will include the description in the help.

Furthermore, we are now reimplementing and reengineering a large number of
models for the ECB. As part of the new developments in IRIS to support
this, there will be other more sophisticated algorithms preserving the sum
of mean available soon.

Best
Jaromir

**Comment by Nic2020** [comment]
Great,

I found it in Eviews User Guide 1, under Frequency Conversion.

Thank you for the information.

Nicholas
