### ISSUE TITLE
The ordering in get(m,'Xvector') and get(m,'Xdescriptions') do not match

### ISSUE THREAD

**Issue by ripatti** [IRIS-Solutions-Team/IRIS-Toolbox#233]
Suppose I want to make script that is based on the transition variables, which I will get by using
xvars = get(m,'Xvector');
The corresponding descriptions for these variables can be get from 
xdesc = get(m,'Xdescriptions');
Unfortunately, the ordering is not the same. 

Fortunately, I can simulate the model and get the related description from
get(d.myXvar,'comment')
Is this the only way? Or can I get the description directly from the model object?

Cheers,
Antti

**Comment by jaromir-benes** [comment]
Hi Antti

You are actually mixing up two things here:

* get(m, 'XVector') returns the list of variables, including their
auxiliary lags and leads (needed to express the transition equation as a
first-order difference equation), ordered exactly as they appear in the
transition vector (aka the vector of state variables). This is, for
instance, the order of the rows and columns of the T matrix returned by sspace(
). To see what's going on here, try e.g. to introduce a t-2 or t+2
lags/leads into your model.

* get(m, 'XNames') - this is what you want: it returns the list of
variables, plain a simple, no lags, no leads, no nothing, ordered exactly
as they have been declared in the model file. The order then also matches
the descriptions you get from get(m, 'XDescriptions').

Hope this helps
Best
Jaromir

**Comment by ripatti** [comment]
Great, perfect! Thanks a lot. This solves the issue!
Best,
Antti
