### ISSUE TITLE
Draw from prior distribution

### ISSUE THREAD

**Issue by ripatti** [IRIS-Solutions-Team/IRIS-Toolbox#236]
I wonder if there exists an Iris/matlab function to draw from prior distribution using the `EstimSpec` cell array that is used as an input to 'estimate()' function? Or utilising 'distribution' object?

Cheers,
Antti

**Comment by ripatti** [comment]
I can now see that `logdist` class can be used to draw by the command
`a = F([ ],'draw',1,1000);`
Is there similar for `distribution` class?

Following the new tutorial, I used `distribution` class to set the priors. Can I directly change the priors to follow `logdist` class (I am using `fromMeanStd`)?

**Comment by jaromir-benes** [comment]
Hi Antti

From Release-20200303 on, there is a new function `sample( )` for all
distributions in the `+distribution` package, to generate a vector of
random numbers.

e.g.

d = distribution.LogNormal.fromMuSigma(2.5, 0.5);
y = sample(d, 1, 10000)

generates a 1-by-10000 vector of random numbers from a lognormal.

Most distributions (except Normal, LogNormal, and Uniform) require right
now the Statistics Toolbox. We will prepare our own crude algorithm (based
on the rejection method) to generate random numbers for any distribution
without the Statistics Toolbox at some point.

Best
Jaromir

**Comment by ripatti** [comment]
Thanks a lot Mirek! Testing soon.
