### ISSUE TITLE
Blazer solves assigned block if options endogenize/exogenize used

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#238]
```
>> type test

!variables
x=1
!parameters
a
!equations
a=x;
>> [~,~,ans]=blazer(model('test'),'endogenize=','a','exogenize=','x')
ans = 
  Type enumeration
    SOLVE

```

**Comment by jaromir-benes** [comment]
Hi

Presently, the assignment must have the variable (or its log, exp, or unary
minus transformation) on the left hand side, i.e.
x = a;

In the future, we may include a more thorough analysis of the structure of
the equations.

Best
Jaromir

**Comment by ikarib** [comment]
Yes, x = a is assigned correctly if x is endogenous, but if a is swapped with x, then "a = x" should not be solved

**Comment by jaromir-benes** [comment]
Unfortunately, the lexical analysis performed at the time the model object
is being createdinformation only results in this kind of information "This
equation has an endogenous variable separated on the LHS, and the name of
the variable is X, and this can be used in the steady state block-recursive
analysis". The fact that the equation has a parameter separated on the LHS
is not considered.

I will see if a simple modification would help to cover the other case as
well.

Jaromir

**Comment by jaromir-benes** [comment]
The functionality of the blazer has been enhanced to deal with this in Release-20200307.

See the attached test files (remove the txt extensions).

[blazerParameterAssignmentTest.zip](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/4302117/blazerParameterAssignmentTest.zip)
