### ISSUE TITLE
Utilizing !substitutions in preparser commands

### ISSUE THREAD

**Issue by ripatti** [IRIS-Solutions-Team/IRIS-Toolbox#241]
I would benefit in using `!subsitutions` in preparser `!for` loop. (The ultimate reason is to write nested for-loops with the same set of tokens.)

For example, consider the following model file
```
!substitutions
  mystates := x1, x2;
!parameters
  rho
!for 
  ?state = $mystates$
!do
  !transition-variables
  ?state
  !transition_equations
  ?state = rho*?state{-1};  
!end

```
This does not work as expected but results the following preparsed output:
```
!parameters
  rho


  !transition-variables
  x1, x2
  
  !transition_equations
  x1, x2 = rho*x1, x2{-1};

```

**Comment by jaromir-benes** [comment]
Hi Antti

You can use the following:

!parameters
  rho
!for
  ?state = <MyStates>
!do
  !transition-variables
  ?state
  !transition_equations
  ?state = rho*?state{-1};
!end


and then

a = struct( );
a.MyStates = {'x1', 'x2'};
m = Model('filename.model', 'Assign=', a);

Anything enclosed in angular brackets <...> is evaluated (in the preparser)
as a Matlab expression, with the values of the control variables passed
through the Assign= option known. If the underlying variable is a cellstr
array, string array or numeric array, it is expanded to a text list of
their items, - in this case simply x1, x2

You could, for instance, also do ?state = <1:K>, assign a.K=2, and use
x?state in the equations. Or you can go ?state=<upper(MyStates)> to
capitalize the names of your variables, etc....

Hope this helps.

**Comment by ripatti** [comment]
Thanks! Very elegant! This is the best alternative since I can pass the values in model().

**Comment by jaromir-benes** [comment]
Indeed. Note also that it's advisable to use Model( ) objects (capitalized
M) instead of model( ) objects. The latter are kept for bkw compatibility,
but the former ones are receiving all the new algorithms and improvements.

**Comment by ripatti** [comment]
I think I found a bug when using above with `!import` preparser command.

To replicate it, copy paste your above model code into a file (say `mycode.model`), and call it inside another model file file, eg
`!import(mycode.model)`

Iris (version 20200304) throws the following error message
```
Error using Model (line 357)
[IrisToolbox] Error when parsing subs.model
*** Misplaced or invalid time subscript in this equation:
<MyStates>=rho*<MyStates>{-1};


Error in run_subs (line 3)
m = Model('subs.model', 'Assign=', a);
 
```

**Comment by jaromir-benes** [comment]
Thanks for catching this one. Fixed, will be out in the new release later
today.
