### ISSUE TITLE
rmse

### ISSUE THREAD

**Issue by jmhshek** [IRIS-Solutions-Team/IRIS-Toolbox#251]
the function rmse under "DataManagement\@NumericTimeSubsciptable\" has an issue as there are two "pe" in the output.

function [outputRmse, pe, dRmse, pe] = rmse(obs, pred, range, varargin)

**Comment by jmhshek** [comment]
Dear Jeromir,

Thanks for looking into the above issue in advance.

Best regards,
Jimmy

**Comment by jaromir-benes** [comment]
Fixed
