### ISSUE TITLE
Do you know if Iris can solve high dimentional PDEs or FBSDEs

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#252]
Hi Jaromir,

Do you know if this is possible to Iris to solve high dimensional Partial Differential Equation (PDEs) or Forward-Backward Stochastic Differential Equation (FBSDEs).
If yes can you explain us how we can do that with Iris.

For reference we find a document really interesting https://github.com/SciML/NeuralNetDiffEq.jl where someone develops a library for doing that in Julia and we want to know if this kind of tools existing in Iris.

Thanks for your assistance

**Comment by jaromir-benes** [comment]
Hi

The answer is no. Iris operates in discrete time only, and does not handle continuous time models.

Best
Jaromir
