### ISSUE TITLE
convert is not backward compatible

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#261]
In older versions of IRIS, function `convert` was removing NaNs by default when converting from high frequency to lower frequency series. Now, we need to set `'RemoveNaN=',true`.

**Comment by jaromir-benes** [comment]
Yes, that was a deliberate change with a backward compatibility warning in [Release-20180318](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/releases/tag/Release-20180318), see  explanation in #123.
