### ISSUE TITLE
please add vintage_dates to databank.fromFred

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#263]
This would useful to reconstruct the datasets to replicate results from published papers.
It would be also useful to pass a comma separated string of YYYY-MM-DD formatted dates in history (e.g. 2000-01-01,2005-02-24) to create series with multiple columns for each vintage date.

https://fred.stlouisfed.org/docs/api/fred/series_observations.html#vintage_dates

https://fred.stlouisfed.org/docs/api/fred/series_vintagedates.html

**Comment by ikarib** [comment]
multiple comma separated dates would be even better to produce multi column series

**Comment by jaromir-benes** [comment]
Nice idea, WIll implement.
