### ISSUE TITLE
get(m,'Wrt') does not work?

### ISSUE THREAD

**Issue by ripatti** [IRIS-Solutions-Team/IRIS-Toolbox#267]
>> d = get(m, 'Derivatives');
Error using model/get (line 298)
[IrisToolbox] Error
*** This is not a valid get query to model object: Derivatives
 
>> get(m,'Wrt')
Error using model/get (line 298)
[IrisToolbox] Error
*** This is not a valid get query to model object: Wrt

**Comment by jaromir-benes** [comment]
Hi Antti

I needed to create a new option for this, as the internal structure of the
gradients changed in IrisT. In the latest release,

g = get(m, 'Gradient')

will now get you a nested struct

g.Dynamic
g.Steady

each being an n-by-2 cell array where n is the number of equations.

g.Dynamic{k, 1} is the gradient of the k-th dynamic equation w.r.t. to all
variables that occur in that equation (including their respective lags and
leads). This gradient (as before) is a function handle returning a
vector of all derivatives for that equation at once.
g.Dynamic{k, 2} is the list of variables and the order in which the
derivatives occur in g.Dynamic{k, 1}.

Same goes for g.Steady - except that the equations that don't have their
steady version (i.e. a double exclamation point mark...) have the
respective gradient position empty - in that case, the steady equation is
identical to the dynamic equation.

Hope this helps.

Jaromir

**Comment by jaromir-benes** [comment]
Fixed in 20200828.

**Comment by ripatti** [comment]
Great! Thanks a lot.

Antti

pe 28. elok. 2020 klo 18.39 Jaromír Beneš (notifications@github.com)
kirjoitti:
