### ISSUE TITLE
function 'convert' in newest version IRIS 20200811 does not work with MATLAB2019 or earlier

### ISSUE THREAD

**Issue by xtang8** [IRIS-Solutions-Team/IRIS-Toolbox#270]
To whom it may concern,

I am writing to let you know that the function 'convert' in IRIS202008XX does not work with MATLAB2019 or earlier version because it called 'matches' in MATLAB, which does not exist in MATLAB2019 or earlier version. It means any functions in new  IRIS202008XX,  which call 'matches' in MATLAB, those functions will not work with MATLAB2019 or earlier version.

Sincerely,
Xiaobin Tang from Bank of Canada

**Comment by jaromir-benes** [comment]
Thanks, Xiaobin. This issue has already been resolved in the current master
branch, and will be part of the next release. Best, Jaromir

**Comment by jaromir-benes** [comment]
Thanks, Xiaobin. This issue has already been resolved in the current master branch, and will be part of the next release. Best, Jaromir
