### ISSUE TITLE
Bug: subsasgn for a model object doesn't work

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#274]
Hi Jaromir,

The subsagn of model doesn't work anymore as mentionned in the doc (model/subsagn) . Do you think is it possible to fix the bug?

Setup: 
-	IRIS 2020-10-07 release
-	MATLAB R2020a

Function: 
model/subsasgn

% ## Example ##
%
% Expand the number of parameter variants in a model object that has
% initially just one parameter variant:
%
%     m(1:10) = m;

 
![bug_subsasgn_model](https://user-images.githubusercontent.com/22647406/95468626-b5f79c00-094c-11eb-8671-6d56011cbe39.png)

**Comment by jaromir-benes** [comment]
Hi - the parenthesis based syntax for this was unfortunately causing some
problems so I have removed it in the end.
Instead, please use the following command

m = alter(m, 10);

That is safe to work.

Best,
Jaromir
