### ISSUE TITLE
Forgotten 'k'

### ISSUE THREAD

**Issue by jvlcekatcz** [IRIS-Solutions-Team/IRIS-Toolbox#275]
Unrecognized function or variable 'k'.

**Error in TimeSubscriptable.createDateAxisData>backwardCompatibilityDateFormat (line 101)**
        **replacement = [ ];k**

Error in TimeSubscriptable.createDateAxisData (line 36)
    dateFormat = backwardCompatibilityDateFormat(dateFormat, timeFrequency);

Error in Series.implementPlot (line 58)
    = TimeSubscriptable.createDateAxisData(axesHandle, dates, opt.PositionWithinPeriod,
    opt.DateFormat);

Error in Series/plot (line 117)
[varargout{1:nargout}] = Series.implementPlot(@plot, varargin{:});

**Comment by jaromir-benes** [comment]
Thanks, fixed - will out with the next release.
