### ISSUE TITLE
empty tokens in !for loops

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#29]
Please allow empty tokens in !for loops.  If the model has many identical equations for sticky and flexible price economies, then it would be easier to add suffix "_f" only for flexible variables without any suffix for sticky variables.

**Comment by jaromir-benes** [comment]
Create empty tokens by creating a cell array of strings (where one string is an empty string) enclosed in angle brackets. The other, non-empty tokens can be place either together with the empty string inside the cell or outside as usual.

Either of the two examples will work:

```
!for
    ? = <{'', '_f'}>
!do
    ...
!end
```

or

```
!for
    ? = <{''}>, _f
!do
    ...
!end
```

**Comment by ikarib** [comment]
The old syntax works fine:
```
>> type test.model

!for '',_f
!do
!transition_variables
x?
!transition_equations
x?=1;
!end
>> get(model('test.model'),'xEqtn')

ans = 

    'x=1;'    'x_f=1;'

```

This new syntax doesn't work:
```
>> type test1.model

!for ?=<{'','_f'}>
!do
!variables
x?
!equations
x?=1;
!end
>> model('test1.model')
IRIS Toolbox Error when parsing test.model
*** Misplaced or invalid time subscript in this equation: x<{=1;
```


```
>> type test2.model

!for ?=<{''}>,_f
!do
!variables
x?
!equations
x?=1;
!end
>> model('test2.model')
IRIS Toolbox Error when parsing test.model
*** Misplaced or invalid time subscript in this equation: x<{}>=1;
```

**Comment by jaromir-benes** [comment]
It looks like you might be again using an older version or so... It runs ok on my computer.

**Comment by ikarib** [comment]
Thanks.
