### ISSUE TITLE
myinpdata - illegal use of 'else'

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#3]
Function:  casslib\@varobj\myinpdata.m  ... starting 'if' statement is missing

_Error using FAVAR/myinpdata
Error: File: myinpdata.m Line: 24 Column: 1
Illegal use of reserved keyword "else"._

**Comment by jaromir-benes** [comment]
Fixed in 20170206-Beta
