### ISSUE TITLE
growth in stationary models

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#30]
Please remove imaginary growth rates in stationary models when log_variables are present.
> test.model:
```
!transition_variables
x
!log_variables
x
!transition_equations
x=1;
```

```
>> m=sstate(model('test.model'));
>> m.x

ans =

   1.0000 + 1.0000i
```

To fix this, please add line 68 to classlib\\@model\steadyNonlinear.m
```
gx(ixLog & gx == 1) = 0;
this.Variant{iAlt}.Quantity = lx + 1i*gx;
```

**Comment by jaromir-benes** [comment]
Use either of these two methods to fetch steady levels (real parts) of the steady state description stored within model objects:

```
s = get(m, 'SteadyLevel')
s.x
```

or

```
set(m, 'Behavior:DotReferenceFunc=', @real)
m.x
```
