### ISSUE TITLE
Symbolic representation of either the state-space

### ISSUE THREAD

**Issue by frnix** [IRIS-Solutions-Team/IRIS-Toolbox#304]
Hi Jaromir,

I would appreciate your response to a related question: To your knowledge, is IRIS currently able to generate a symbolic representation of either the state-space formulation of a given DSGE model, or of the log-linearized version thereof? If not, is there any capacity to generate them?

Best regards,
Francis

**Comment by jaromir-benes** [comment]
Hi Francis

There is absolutely no way to get the symbolic/analytical representation of the state-space/solution matrices for a DSGE. The solution is based on a generalized Schur decomposition of the underlying unsolved system matrices (this is neded to integrate away the future expectations). The Schur decomposition is an extremely complex calculation based on numerical iterations with no closed-form solution available; in addition, it is also non-unique (and may be non-convergent in some rare cases).

The only pieces of information you can get (and there are IrisT functions for these) are:

* the analytical/symbolic derivatives of the unsolved/original equations w.r.t. the individual variables

* numerical matrices describing the unsolved system given your parameters (these matrices are directly based on the above derivatives)

* numerical matrices describing the solved state-space matrices given your parameters

Best
Jaromir

**Comment by frnix** [comment]
Hi Jaromir,

Thank you for the clear and prompt response. It validates my expectations.

Best,
Francis
