### ISSUE TITLE
x13 error in r2019b

### ISSUE THREAD

**Issue by tmotl2** [IRIS-Solutions-Team/IRIS-Toolbox#311]
The following error occurs in r2019b, but works fine in r2020b:

Invalid default value for argument
'Series_Precision'. Index in position 1 exceeds
array bounds (must not exceed 1).
Error in x13.season
Error in getInitcondFromData (line 156)
  db.prof = x13.season(db.prof);

Replicate by loading [this](https://drive.google.com/file/d/1K5RTvR56X788Q8d0K1mv1CLOe2zAgGZJ/view?usp=sharing) matfile and running:
x13.season(ts)

**Comment by jaromir-benes** [comment]
Fixed on master. Will be out with the next release.
