### ISSUE TITLE
run(defaultBlazer);

### ISSUE THREAD

**Issue by Nic2020** [IRIS-Solutions-Team/IRIS-Toolbox#318]
I tried to run the tutorial [Tutorial-Simple-SPBC-Model](https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model) / [run09_nonlinearSimulation.m](https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model/blob/master/run09_nonlinearSimulation.m) and I get this bug.
![run_defaultBlazer_bug](https://user-images.githubusercontent.com/30166151/170790813-bf3e55f0-61bb-40ac-8084-70f3e4dc72b9.png)

**Comment by tosapola** [comment]
Yes, it happens when simulate using "stacked" or "period". 
Please fix this @jaromir-benes .

**Comment by jaromir-benes** [comment]
Fixed

**Comment by tosapola** [comment]
@jaromir-benes Hi,
This seems not to be solved yet.
Matlab says it is confused by a variable named "run" at the top of simulate.m and the function "run" in the bottom.

Thanks!

**Comment by jaromir-benes** [comment]
Hi - can you make sure you have some recent Iris (either the tip of the
bleeding branch, or the stable release)? The variable named "run" has been
removed/renamed some time back and no longer exists in Model/simulate...
Best, Jaromir

**Comment by tosapola** [comment]
Now I see. Github issue. 
You already changed it.
But it's my fault that I used to download master.zip.
Solved.

Thank you so much.

**Comment by jaromir-benes** [comment]
I strongly recommend using git to *clone* the IrisT repo locally on your
computer (instead of downloading) - about a million times more convenient
when updating, switching between versions, comparing, etc. Best J
