### ISSUE TITLE
slow convergence in sstate

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#32]
Please add the following options to the IRIS steady state solver

- `lambda = 0` (turn off optimal search)
- `d = -j \ f` (full rank jacobian, sparse)
- `norm(f,Inf)` (maximum norm for residuals)

**Comment by jaromir-benes** [comment]
* New options Lambda= and FunctionNorm=
* Set Lambda= to an empty array [ ]  to run pure Newton, or to a vector of lambdas to choose a hybrid step.
* Choose function norm by setting FunctionNorm= to 1, 2, or Inf, or to a user supplied function handle.
