### ISSUE TITLE
Error in find function

### ISSUE THREAD

**Issue by ljubicabor** [IRIS-Solutions-Team/IRIS-Toolbox#320]
Running Iris (20220529) on Matlab2018a throws this error:

> Undefined function 'find' for input arguments of type 'string'.
> 
> Error in x13.splitDataColumns (line 14)
>     first = find(inxFiniteData(:, i), 1, "First");
> 
> Error in x13.season (line 343)
> [dataColumns, startDates, freq] = x13.splitDataColumns(inputSeries);
> 
> Error in rs_process_data>x12_sa (line 146)
>           db.(i_sa) = x13.season(db.(i),Inf,specs{:});
> 
> Error in rs_process_data (line 114)
> dm = x12_sa(dm,{});
> 
> Error in algo_process_data (line 45)
>     rs_process_data(dt,dm,dq,dy,dft,dfm,dfq,dfy,desc,attributes,adbs);

**Comment by jaromir-benes** [comment]
Fixed
