### ISSUE TITLE
simulate command fails

### ISSUE THREAD

**Issue by tmotl2** [IRIS-Solutions-Team/IRIS-Toolbox#327]
See error message below. Using R20b and stable branch.

Files to reproduce are in BaM macropru repo, messr-v0, file simulateCovid.m

Unrecognized function or variable 'anticipatedE'.
Error in simulate.Rectangular/flat (line 63)
if isempty(anticipatedE) && isempty(unanticipatedE)
Error in Model.simulateStacked (line 21)
        flat(rect, data);
Error in Model/simulateFrames (line 156)
    [exitFlag, dcy] = func(simulateFirstOrderFunc, rect, data, blazer, frame);
Error in Model/simulate (line 365)
    [~, outputYXEPG{i}] = simulateFrames(this, systemProperty, i, false);
Error in simulateCovid (line 73)
[s0, info] = simulate(m, dbinit, simRange, "prependInput", true, ...

**Comment by jaromir-benes** [comment]
Been fixed on bleeding. Use either the official release commit on stable or the tip of bleeding. J
