### ISSUE TITLE
user-supplied solver

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#33]
Line 215 of +solver\\+block\Block.m
> [z, exitFlag] = this.Solver(@objective, z0);

should be changed to
> [z, exitFlag] = this.Solver(fnObjective, z0);

Line 94 of +solver\\Options.m
> isGradient = false;

should be changed to
> isGradient = true;

Otherwise, neither analytical nor numerical gradient is returned if user-supplied steady state solver is given:

> m=sstate(m,'solver=',@newton);

I am supplying own solver because your Newton solver is making two function evaluations per step instead of one. You need to add `fnCount = fnCount + 1;` to makeNewtonStep()

**Comment by jaromir-benes** [comment]
See the attached files (remove .txt extensions)

[test_steady_solver.model.txt](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/793210/test_steady_solver.model.txt)
[test_steady_solver.m.txt](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/793211/test_steady_solver.m.txt)

 for how to use PrepareGradient= and SpecifyObjectiveGradient= options in various contexts (IRIS versus user-supplied solvers).
