### ISSUE TITLE
Historical tunes in qpm

### ISSUE THREAD

**Issue by trcrztw** [IRIS-Solutions-Team/IRIS-Toolbox#336]
Hi,
please help understand how to add historical tunes to variables in basic quarterly projection model. For example I have 4 basic equations for my home economy and ar(1) equations for foreign country. For foreign economy all trends are calculated using hpf, but for home economy - kalman filter is used. I want to add a negative shock to gdp potential for 2020q2 and then make forecasts. I tried some thoughts but to no effect. If I use fcast_plan for something earlier then t, I get nothing. For example I add negative shock to 2020q2 and make forecast starting 2020q3, there is no effect. If I use 2020q3 as negative shock to forecast 2020q3 it works.
Thank you!!!

**Comment by jaromir-benes** [comment]
Hi - could you please move this question to the Discussions section (instead of the Issues section). I'll be happy to respond to it there. Thank you, Jaromir

**Comment by trcrztw** [comment]
Wrong section. Question moved to Discussion section.

**Comment by trcrztw** [comment]
Wrong section. Question moved to Discussion section.
