### ISSUE TITLE
getComments function missing

### ISSUE THREAD

**Issue by kbankowski** [IRIS-Solutions-Team/IRIS-Toolbox#342]
`DataManagement\+databank\+backend\extractSeriesComments.m` is missing `getComments` function

**Comment by jaromir-benes** [comment]
Fixed in the head of bleeding and stable.

**Comment by kbankowski** [comment]
Iris does not seem to recognize the function; see a little example below

`aaa = Series(yy(2021):yy(2023), [2,3,4])`

`getComments(aaa)`

`Unrecognized function or variable 'getComments'. `

**Comment by jaromir-benes** [comment]
Did you pull the latest commit from today?
