### ISSUE TITLE
Logistic distribution - Gamma & Inv Gamma

### ISSUE THREAD

**Issue by beremtz** [IRIS-Solutions-Team/IRIS-Toolbox#345]
I am trying to update an old code (from 2015) that used

logdist.gamma & logdist.invgamma

If I do:
logdist.gamma(0.7,0.3)
I got:
Unable to resolve the name logdist.gamma.

similar for logdist.invgamma

Has the syntax changed? Any alternative to work around this?

**Comment by jaromir-benes** [comment]
Hi - its' distribution.Gamma.fromMeanStd(mean, std). Best, J

**Comment by Lch1710** [comment]
logdist.gamma=distribution.Gamma.fromMeanStd(mean, std), how about logdist.invgamma?

**Comment by jaromir-benes** [comment]
Hi

Note please first that the name should be `distribution.Gamma` (`logdist`
is just a legacy name, slightly confusing, kept for backward
compatibility)...

For inverse gamma, it's `distribution.InvGamma` (the names of objects in
Matlab are capitalized or, in general, PascalCased...).


Best
Jaromir
