### ISSUE TITLE
Was logdist dropped? Is there an alternative?

### ISSUE THREAD

**Issue by guzmangt** [IRIS-Solutions-Team/IRIS-Toolbox#372]
I noticed that logdist isn't distributed with the toolbox starting with 20220918. Has it been dropped on purpose? If so, what alternative can I use?

**Comment by jaromir-benes** [comment]
HI - it's been simply renamed to distribution.XXX a while back to make the
name more consistent with what the +distribution package has evolved to do.
Look e.g. the example in run13_estimateParams.m in
https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model or
run06_estimateParameters.m in
https://github.com/IRIS-Solutions-Team/Tutorial-System-Priors.

Best,
J

**Comment by guzmangt** [comment]
Got it, thank you so much for the quick answer!
