### ISSUE TITLE
Tseries 

### ISSUE THREAD

**Issue by Usukhbayar13** [IRIS-Solutions-Team/IRIS-Toolbox#381]
I  use tmp = tseries(get(x,'first') + (-12:-1),1); with old version of IRIS to create series 12 period before first period of "x" . Now i want to convert this code to Iris 23. When i use series, it does not work. Pls help me. How can i convert this code to compatible with new version of Iris .

**Comment by jaromir-benes** [comment]
tmp = Series(getStart(x)+(-12:-1), 1)

Mind the capitalization of the "Series" class name.

**Comment by Usukhbayar13** [comment]
thanks a lot
