### ISSUE TITLE
grouping function issue

### ISSUE THREAD

**Issue by Usukhbayar13** [IRIS-Solutions-Team/IRIS-Toolbox#382]
function g = prepareGrouping(this, g, type, opt)

add = cell(1, 0);

if startsWith(type, "s", "ignoreCase", true)
    g.Type = 'shock';
    ixType = this.Quantity.Type==31 | this.Quantity.Type==32;
    if opt.IncludeExtras
        add = { ...
            model.CONTRIBUTION_INIT_CONST_DTREND, ...
            model.CONTRIBUTION_NONLINEAR, ...
            };
    end

elseif startsWith(type, "m", "ignoreCase", true)
    g.Type = 'measurement';
    ixType = this.Quantity.Type==1;

end

g.List = [this.Quantity.Name(ixType), add];
g.Label = [this.Quantity.Label(ixType), add];
g.IsLog = access(this, "is-log");

end

 I use this code with iris 14 to grouping shocks. But "access" function  is not working on IRIS 23. How the 'access' changed in IRIS23?

**Comment by jaromir-benes** [comment]
Hi - the "access" function is working in the latest Iris - you can check
this by simply running

>> access(m, "is-log")

on the command line for any model....

Can you please give me more details about the error message you get when
calling "prepareGrouping"?

J

**Comment by Usukhbayar13** [comment]
here is the error message:
Incorrect number or types of inputs or outputs for function 'access'.

Error in model/prepareGrouping (line 30)
g.IsLog = access(this, "is-log");

Error in grouping (line 143)
            this = prepareGrouping(m, this, type, opt);


g = grouping(m,'shock');

**Comment by jaromir-benes** [comment]
What release/commit of Iris is this?

**Comment by Usukhbayar13** [comment]
maybe the problem was on model file. When I use 'Model.fromFile' instead of 'model' , it works. thanks for reply

**Comment by jaromir-benes** [comment]
Yes, exactly - you need to use the new "Model" objects, not the old "model"
(mind the capitalization, same goes for plan versus Plan, tseries versus
Series). Best, J
