### ISSUE TITLE
Endogenize, exogenize

### ISSUE THREAD

**Issue by Usukhbayar13** [IRIS-Solutions-Team/IRIS-Toolbox#384]
This error message appears when I am doing forecast with new version of Iris. Please help me. What is the problem and how i fix it?

```
Error using Plan.implementExogenize
The value of 'datesToExogenize' is invalid. It must satisfy the function: @(x)isequal(x,@all)||validate.date(x).

Error in extend.InputParser/parse (line 59)
            parse@inputParser(this, varargin{:});

Error in Plan/implementExogenize (line 219)
            pp.parse(this, dates, names, varargin{:});

Error in Plan/exogenize (line 21)
this = implementExogenize(this, dates, names, opt.SwapLink, unmatched{:});

Error in driver_forecast_baseline (line 215)
sp = exogenize(sp,{'d4l_cpi_f'},startfcast:startfcast+3);
```

Here is the code I am using.

```
sp = Plan(m, range);

sp = exogenize(sp,{'d4l_cpi_f'},startfcast:startfcast+3)
sp = endogenize(sp,{'shock_dl_cpi_f'},startfcast:startfcast+3);
```
And i have another question. If i use 'plan' instead of 'Plan', wil exogenize and endogenize work?

**Comment by jaromir-benes** [comment]
In the exogenize/endogenize functions of the new Plan objects, you need to
use the dates first, and the list of names (preferably specified using the
string arrays, not cellstr arrays), e.g.

sp = endogenize(sp, startfcast:startfcast+3, ["shock_dl_cpi_f",
"shock_xxx"]);

**Comment by Usukhbayar13** [comment]
Thank you very much Jaromir. It works.
