### ISSUE TITLE
Plan and anticipate

### ISSUE THREAD

**Issue by Usukhbayar13** [IRIS-Solutions-Team/IRIS-Toolbox#385]
When i use this simulation code with new version of IRIS, this  error message is appearing. It works perfectly with IRIS 14, but does not work with new version of IRIS. Why does this happening? Maybe some functions have been renamed?
Or with new version of IRIS we cant use these functions at the same time?  
Code:
`sim = simulate(m,dbinitial,fcastrange,'anticipate', true,'Plan',sp,'prependInput',true);`

Error:
```
Error using Model/simulate
[IrisToolbox] Error
*** Options Plan= and Anticipate= cannot be used at the same time.


Error in driver_forecast_baseline (line 328)
sim = simulate(m,dbinitial,fcastrange,'anticipate', true,'Plan',sp,'prependInput',true);
```

**Comment by jaromir-benes** [comment]
When using a plan, specify the default anticipation status in the Plan
object. The anticipate option cannot be used simultaneously with the plan
option.

**Comment by Usukhbayar13** [comment]
Thank you for quick reply, Jaromir. This helped me a lot.
