### ISSUE TITLE
FEVD in sign restricted SVAR

### ISSUE THREAD

**Issue by michall23full** [IRIS-Solutions-Team/IRIS-Toolbox#41]
I have a question regarding FEVD in sign-restricted SVAR. I identified only two shocks and then computed FEVD for 5 periods for closest-to-median draw, but it gave me a series of 4x4x5 matrices, like in the Cholesky SVAR.

How can I calculate FEVD for structural shocks identified by sign restrictions ?

**Comment by jaromir-benes** [comment]
When you use sign restrictions, IRIS uses a resampling algorithms to randomly draw structural matrices that identify all shocks while satisfying you restrictions. This means that if you leave some shocks "free" (with no restrictions) their identification will be just something random. Simply ignore or discard them.

**Comment by michall23full** [comment]
Thank you for the explanation.

**Comment by jaromir-benes** [comment]
I'm closing the issue now. If you have any further questions relating to sign restrictions in VARs, feel free to reopen it. Jaromir
