### ISSUE TITLE
produce_forecast.m in VAR intro tutorial creates empty charts

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#42]
produce_forecast.m in VAR intro tutorial creates empty charts. 

Line 556 of +dbplot\dbplot.m
```
    case 'errorbar' % Error bar graph.
        [~, ~, range, data] ...
            = errorbar(range, x{:}, varargin{:}, funcArgs{:});
```
should be changed to
```
            = errorbar(range, x{:}{:,1}, x{:}{:,2}, varargin{:}, funcArgs{:});
```

**Comment by jaromir-benes** [comment]
This is strange. I don't have any problems like this on my computer... To be on the safe side, could you please check the tutorial out of the repo, https://github.com/IRIS-Solutions-Team/Tutorial_Introduction_to_VARs, and give it a try again? If the problem still arises, could you email me your Matlab version, verify the IRIS version, and possibly attach screenshots of the empty figure windows? Thanks...

**Comment by ikarib** [comment]
Please update the new links to VAR tutorials at the wiki:
https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/wiki/Tutorials
