### ISSUE TITLE
shock decompositon - regrouping

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#5]
I am running shock decomposition, and then do grouping of shocks

db = simulate(m,d,rng_res,'anticipate',false,'plan',simplan,'contributions',true);  

g = grouping(m,'shock'); 
    g = addgroup(g,'Supply',...
                        {'shock_dl_cpi'});
    g = addgroup(g,'Demand',...
                        {'shock_l_y_gap'});
   ...

  [dbg,leg] = eval(g,db);  

The database 'db'  contains also  Initial conditions and Nonlinear component.  In old IRIS, after regrouping (eval) ... these two components are still there (last two columns)

In new IRIS those two components are summed up and have name 'Other'.

Is it new feature designed by purpose?  
We were used to plot those initial conditions by adding legend name by ourselves.

**Comment by jaromir-benes** [comment]
This was indeed meant to be a new feature/improvement. I roll it back to maintain bkw compatibility, and introduce a new option `IncludeExtras=` set to `false` by default, which reproduces previous behavior. If changed to `true` the two extra contributions, `Init+Const+Dtrend` and `Nonlinear` are included in the grouping object.

**Comment by jaromir-benes** [comment]
Fixed in 20170207-Gamma.
