### ISSUE TITLE
Using rexp with '*' operator for databases

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#55]
It would be great if we can do something like...
`d * rexp('^x1')`
to keep only the database entries with prefix 'x1', although this can be done by using dbnames().

Also great for the followings if we can use rexp:
'-' (minus) operator for databases
db2array()
db2tseries()

**Comment by ikarib** [comment]
also please make overloaded operators `-`, `*` and `+` to preserve ordering from the original database instead of sorting
