### ISSUE TITLE
Exogenous variables in VAR

### ISSUE THREAD

**Issue by gbp17** [IRIS-Solutions-Team/IRIS-Toolbox#57]
Hi, 
Adding an exogenous variable to a VAR works fine with the following code;
```
v = VAR(series,'exogenous=','exovariable1');
[v,vd] = estimate(v,vdata,rngEst, ...
   'order=',p,'const=',true);  
```

However, the bootstrap code below gives an error;
```
bd2 = resample(v,vd,range(1)+p:range(end),nboot,'wild=',true,'progress=',true); 
bvv2 =  VAR(series,'exogenous=','exovariable1');
bvv2=estimate(bvv2,bd2,range(1):range(end),'order',p,'const=',true); %
```

Error using horzcat
Dimensions of matrices being concatenated are
not consistent.

Error in VAR/mystackdata (line 63)
            X0 =
            [X0,XInp{iGrp},nan(nx,p,nAlt)];
            %#ok<AGROW>

Error in VAR/estimate (line 163)
[y0,k0,x0,y1,g1,ci] =
mystackdata(This,y,x,opt);

Can you please help me with that? Thanks
T.

**Comment by jaromir-benes** [comment]
Hi

Please update your IRIS to the latest Beta (from this GitHub site) and it should run OK.

Let me know if the issue (or some other) persists.

Best,
Jaromir

**Comment by gbp17** [comment]
Thanks Jaromir
