### ISSUE TITLE
Octave compatibility

### ISSUE THREAD

**Issue by michall23full** [IRIS-Solutions-Team/IRIS-Toolbox#58]
I see you have put some workarounds for Octave in the code. Does it mean the newer editions are compatible with Octave or it is still necessary to rely on 20140719 version ?

**Comment by nul0m** [comment]
Hi,

No, Octave compatible version is still based on the IRIS as of July, 2014. Although I've made this version compatible with the latest official version of Octave. Here is the new IRIS4Octave repo: https://github.com/OGResearch/iris4octave

**Comment by michall23full** [comment]
Oh, so I see it works with Octave 4.2.1 now, Thanks a lot
