### ISSUE TITLE
Function 'spy' squeezes graph

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#6]
Function 'spy' squeezes graph.  Here, used in FAVAR estimation file.

_F = figure('visible','on');
  subplot(121);
    Y = db2tseries(dv,list,smplfull);
    spy(Y,'markersize',18);
    title('Original database');
    highlight(smplf);
    
  subplot(122);
    Y2 = db2tseries(fdb.mean,list,smplfull);
    spy(Y2,'markersize',18);
    title('Filtered database');
    highlight(smplf);_

[selection_old.pdf](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/755580/selection_old.pdf)
[selection_new.pdf](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/755581/selection_new.pdf)

**Comment by jaromir-benes** [comment]
New option `Squeeze=` introduced in `tseries/spy`. Set to `false` by default to reproduce previous behavior. If changed to `true` the `PlotBoxAspectRatio` property of the axes object is adjusted to squeeze the chart.

**Comment by jaromir-benes** [comment]
Fixed in 20170206-Gamma.
