### ISSUE TITLE
model command error

### ISSUE THREAD

**Issue by gbp17** [IRIS-Solutions-Team/IRIS-Toolbox#60]
Hi Jaromir,
I get the following error with Version 20170330-Beta+Matlab 2014b. Is it a compatibility issue? Thanks

`m = model('simple_SPBC.model');`
Error using max
Dimension argument must be a positive integer scalar
within indexing range.

Error in model/myd2s (line 38)
maxMaxSh = max(maxSh, [ ], 'OmitNan');

Error in model/build (line 77)
this = myd2s(this, opt);

Error in model (line 602)
                    this = build(this, opt);

**Comment by jaromir-benes** [comment]
Hi,

This is indeed a Matlab compatibility issue. I didn't realize the 'OmitNan' flag was introduced later than 2014. Is it difficult for you to switch to a newer version of Matlab? Otherwise, I will rewrite that piece of code. Let me know.

Best
Jaromir

**Comment by gbp17** [comment]
Thanks Jaromir, I will be updating soon.

**Comment by nul0m** [comment]
the issue was fixed some time ago
