### ISSUE TITLE
Bug in systempriors?

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#63]
Hi,

I got the following errors when trying to use systempriors on the latest beta.
This piece of code works well with previous stable release.

Thx,
T.

> Error using regexprep
> Evaluation of 'replaceFunc($1)' failed:
> 
> No appropriate method, property, or field 'Quantity' for class
> 'systempriors'.
> 
> Error in systempriors/prior>parseNames (line 320)
>     def = regexprep(def, ptn, '${replaceFunc($1)}');
> 
> Error in systempriors/prior (line 128)
> def = parseNames(this, def);
> 
> Error in estim_lambdas (line 64)
> S = prior(S,'.y20_ss',logdist.normal(ymean(find(tau==20)),0.02), ...

**Comment by jaromir-benes** [comment]
Fixed in repository.
