### ISSUE TITLE
dbplot with mixed frequency

### ISSUE THREAD

**Issue by gbp17** [IRIS-Solutions-Team/IRIS-Toolbox#64]
Hi,
Is it possible to plot data with mixed frequencies using dbplot? If not, it will be great to have this feature
in the new release. Please let me know if there is already a way to do it since the following doesn't seem to work.

Thanks

```
d.x=tseries(mm(1990,1):mm(2000,1),@rand)
d.y=tseries(qq(1990,1):qq(2000,1),@rand)
dbplot(d)
```
Warning: IRIS Toolbox Warning @ dbplot:dbplot.
*** Error plotting x.
	Matlab says: IRIS Toolbox Error @ inp:generic:assign.
*** Expecting input argument 'Time Series' but none found or its value
fails validation.
*** Error plotting y.
	Matlab says: IRIS Toolbox Error @ inp:generic:assign.
*** Expecting input argument 'Time Series' but none found or its value
fails validation.

**Comment by nul0m** [comment]
`dbplot` doesn't support mixed frequencies yet.

**Comment by jaromir-benes** [comment]
Added in Release-20180312. See help on `dbplot`.
