### ISSUE TITLE
square root of inverse gamma distribution

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#65]
In Dynare we usually use two types of inverse gamma distributions: INV_GAMMA2_PDF for variance and INV_GAMMA1_PDF for the standard deviation of the transition or measurement shock. Please see the derivations at https://archives.dynare.org/phpBB3/download/file.php%3Fid=5955

IRIS currently only has type-2 distribution logdist.invgamma used only for the variance. Please add type-1 distribution for the standard deviation.

**Comment by jaromir-benes** [comment]
I have accepted the pull request, however, for bkw compatibility, I will rearrange the inv gamma distributions as follows in the next pre-release:

1. I will bring back the function called `logdist.invgamma` to what it used to be before.
2. I will introduce two new functions, `logdist.invgamma1` and `logdist.invgamma2`, with the latter one simply shadowing the existing `logdist.invgamma`.

Best
Jaromir

**Comment by ikarib** [comment]
I prefer how Dynare sets inv_gamma_pdf to inv_gamma1_pdf

**Comment by jaromir-benes** [comment]
Bkw compatibility, the bitch of all of us :)
