### ISSUE TITLE
estimate command error

### ISSUE THREAD

**Issue by elnoch5** [IRIS-Solutions-Team/IRIS-Toolbox#67]
Hi, I have this code that used to run with Iris Toolbox version 20130523 in Matlab.
_[pEst,pos,~,~,mest] =estimate(m,H,startest:endyear,E,...
    'tolx',1e-8,'tolfun',1e-8,'nosolution=','penalty',...
    'filter=',{'relative',false});_

But when I try to run it in the current versions of Iris and Octave, I get the following error:
_error: 'fields' undefined near line 44 column 10
error: called from
    chkpriors at line 44 column 8
    estimate>doChkPriors at line 445 column 41
    estimate at line 376 column 1_

Is this a compatibility issue? 
Thank you.

**Comment by nul0m** [comment]
The current version of IRIS doesn't work in GNU Octave, please see [here](https://github.com/OGResearch/iris4octave/wiki) for more information
