### ISSUE TITLE
bug in dbsave

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#68]
dbsave doesn't parse options:
line 169 of dbase\dbsave.m should be deleted:
```
varargin = {};
```

**Comment by jaromir-benes** [comment]
Not sure I understand this issue... I don't have this problem (dbsave parses options OK), and there is no line like ```varargin = {};``` in my repo...

**Comment by ikarib** [comment]
sorry. messed up my repo.
