### ISSUE TITLE
Favar estimate command error

### ISSUE THREAD

**Issue by aghambaryan** [IRIS-Solutions-Team/IRIS-Toolbox#69]
When I run the function 
**estimate(a,dbq_llfg,list,starthist:endhist,[RF,QF],'order',PF);**

The following error occurs:
Undefined function or variable 'inpFmt'.
Error in FAVAR/estimate (line 77)
if isempty(this.YNames) && isequal(inpFmt, 'dbase')

**Comment by alexisakov** [comment]
Have the same issue.

**Comment by nul0m** [comment]
Guys, this is most likely related to the way you construct the FAVAR (or DFM in new versions). Please note that you must provide the list of variables during construction, like
```
a = DFM(list); % or FAVAR(list)
```

**Comment by alexisakov** [comment]
Right, that solves it.
