### ISSUE TITLE
FAVAR: different std's of factors

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#7]
FAVAR code:

Old IRIS:
When running kalman filter to fill missing observation I get warning, but it is not the issue. 
`[fw,fdb,fcc,ff,fu,fe] = filter(w,dv,smplfull,'cross',false);`

_Warning: IRIS Toolbox Warning @ obsolete.
*** Using tseries objects as input/output data to/from VAR objectsis obsolete, and will be removed from a future version of IRIS. Use databases (structs) instead._

The problem is  that standard deviations of factors (ff.std) in the old version of IRIS are smaller (for first two factors).
[selection_old_iris.pdf](https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model/files/756262/selection_old_iris.pdf)
[selection_new_iris.pdf](https://github.com/IRIS-Solutions-Team/Tutorial-Simple-SPBC-Model/files/756263/selection_new_iris.pdf)

I do not know, which one is correct. 
Thanks.

**Comment by jaromir-benes** [comment]
It was indeed because of a typo in the new IRIS. Fixed in 20170207-Beta.

**Comment by jaromir-benes** [comment]
Also, do you really still get the warning message? Can you email me the codes pls?

**Comment by MiroslavHlousek** [comment]
The warnings appeared in the old IRIS.   New version runs without warnings..

**Comment by jaromir-benes** [comment]
Ok, thanks.
