### ISSUE TITLE
findtexmf --file-type=exe doesn't work in the newer MikTeX

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#84]
`findtexmf` comman line tool from the newer MikTeX has adjusted the list of types. now what used to be called "exe" is called "executables"
older:
![image](https://user-images.githubusercontent.com/6223985/31376064-f01e2492-ada3-11e7-848f-2503a738f2d3.png)
newer:
![image](https://user-images.githubusercontent.com/6223985/31376091-08fd6c2a-ada4-11e7-8396-c1fc1331fc7c.png)

so now the command `findtexmf --file-type=exe pdflatex` returns an error -- 'Unknown file type'

the solution is simple, let's just explicitly specify the extension `.exe` instead of `exe` or `executables`
either of these works in both versions of the findtexmf:

- `findtexmf --file-type=.exe pdflatex`
- `findtexmf pdflatex.exe`

**Comment by jaromir-benes** [comment]
Will either work with the older versions of MikTeX_

On Tue, Oct 10, 2017 at 10:21 AM, sergey plotnikov <notifications@github.com

**Comment by jaromir-benes** [comment]
?

**Comment by nul0m** [comment]
seems so. i tested it with miktex as of 2015/16.. it’s 2.9.3xxx.
unfortunately i don’t have older miktex to try that out.
вт, 10 окт. 2017 г. в 11:00, Jaromír Beneš <notifications@github.com>:

> ?
>
> On Tue, Oct 10, 2017 at 11:00 AM, Jaromir Benes <jaromir.benes@gmail.com>
> wrote:
>
> > Will either work with the older versions of MikTeX_
> >
> > On Tue, Oct 10, 2017 at 10:21 AM, sergey plotnikov <

**Comment by nul0m** [comment]
so, i've pushed the first option (bb5e286) and it fixes the issue on the latest MikTeX (2.9.6400) and works fine with the MikTeX 2.9.3871. will re-open this issue if we find out the older MikTeXs do not support this.

shall we just specify what is the latest MikTeX version we support?

**Comment by jaromir-benes** [comment]
only if we get some issues from users :)
