### ISSUE TITLE
Series vertcat with empty Series crashes

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#85]
Just try this
```
[Series;Series]
```

I've added a new test to `IRIS-Test/tseries/catTest.m` 
- see the commit, https://github.com/IRIS-Solutions-Team/IRIS-Test/commit/d1d770843d2b4b1f5b1515cfa1084d90ff5a02d1
- and the error stack trace in the test build-log, [TeamCity log](https://teamcity.igpmn.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=535&_focus=2321)

**Comment by jaromir-benes** [comment]
Fixed in repo.
