### ISSUE TITLE
'select' option in tseries/convert for high->low crashes for incomplete years

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#86]
try this:
```
ts = tseries(mm(2010,1:13),@randn);
convert(ts,'q',inf,'select',1)
```
new test for that was just added, see the build log: https://teamcity.igpmn.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=718&_focus=2505

**Comment by jaromir-benes** [comment]
Will fix. Thx.
