### ISSUE TITLE
Estimate with custom solver crashes: problem with 'eye' function

### ISSUE THREAD

**Issue by csehandras** [IRIS-Solutions-Team/IRIS-Toolbox#87]
The 'eye' function has changed in the version of Matlab 2016a. With the previous versions, the 'estimate' function does not run.

please check the latest test results:
https://teamcity.igpmn.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=751&_focus=1842

**Comment by nul0m** [comment]
there was one more (rather minor) bkw compat issue we discovered here -- the name of the option was changed from `'Optimiser'` to `'Solver'` which was not reflected in the documentation

**Comment by jaromir-benes** [comment]
Updated.
