### ISSUE TITLE
new timetable class in R2016b

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#89]
I noticed that iris.startup has a new option --tseries, --Series, --TimeSeries. Why create such new classes? This requires replacing all tseries calls with Series calls. Why not just replace tseries class with built-in timetable as the only time series class? Of course, this would require R2016b, but we just upgraded to R2017a.  This will allow automatic relabeling of axes while zooming in and out of the time series graphs. Why not also replace DateWrapper class with datetime introduced back in R2014b?

**Comment by jaromirbenes** [comment]
The new class Series uses Matlab's datetime objects to label x-axis in plots, so zooming is now possible.

**Comment by ikarib** [comment]
That is so cool! Thank you! Closing now.

**Comment by jaromir-benes** [comment]
The standard class `timetable` does not support even elementary operators (plus, etc.). It is a sealed class, hence it cannot be extended to include this functionality.

The standard `datetime` class is still rather inconvenient and significantly slower when dealing with equally spanned (fixed-duration) dates (yearly, quarterly, etc.). You can use the overloaded `datetime( )` function to convert IRIS dates `(DateWrapper` objects) to `datetime` objects.
