### ISSUE TITLE
lagged or leaded model parameters

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#91]
IRIS parser used to allow for lags and leads of model parameters. It is very convenient when you are planning to promote parameter to a variable in some future versions of the model but do not want to change the equations after that.

Was there any specific reason to discontinue this and how difficult it would be to add this back?

**Comment by jaromir-benes** [comment]
This is a bug, the functionality should be there. I will fix it.

**Comment by jaromir-benes** [comment]
Fixed.
