### ISSUE TITLE
Frequency: number vs. text

### ISSUE THREAD

**Issue by MiroslavHlousek** [IRIS-Solutions-Team/IRIS-Toolbox#95]
Hi,

I have tried IRIS Toolbox-master.  When I use function freq(d) or get(d,'freq') I get text (char), e.g. MONTHLY. In older version of IRIS, I get number, e.g. 12.   It makes problem in compatibility with our own codes.  

Could it be solved somehow. 

Thanks.
Mirek

**Comment by jaromir-benes** [comment]
Hi Mirek

The value returned is actually not a char but an enumeration object of
class Frequency. It is a subclass of double and should behave as a number
in all cases, e.g

f = get(d, 'freq')
f + 1

should give you 13 right away

Let me please now exactly under what circumstances it creates problems...

Jaromir

**Comment by MiroslavHlousek** [comment]
Hi Jaromir,

oh, I see. Thanks for explanation. I use the 'f' in connection with colon operator, and it makes this error:

Colon operator not defined for an enumeration class.
Error in calculate_growth_from_overlapping_growths (line 21)
  for i = 1:f

Thanks.
Mirek

**Comment by jaromir-benes** [comment]
OK. I’ll make it possible.

**Comment by jaromir-benes** [comment]
In the meantime, you can use +f whenever you need f to be treated as a
number, e.g. 1:+f.

**Comment by MiroslavHlousek** [comment]
Thanks, yes I have already bypassed by  f+1-1  :)

M.

**Comment by jaromir-benes** [comment]
f+0 would have saved you two key strokes :)
